[package]
name = "windfarm-monitoring"
version = "0.1.0"
edition = "2021"
authors = ["Joerg Zeidler <joerg.zeidler@conplement.de>", "Jan Zachmann <jan.zachmann@conplement.de>"]
repository = "git@github.com:ICS-DeviceManagement/windfarm-monitoring.git"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azure-iot-sdk = { git = "ssh://git@github.com/ICS-DeviceManagement/azure-iot-sdk.git", tag = "0.8.1", features = ["module_client"] }
sd-notify = { git = "ssh://git@github.com/ICS-DeviceManagement/sd-notify.git", tag = "v0.5.0", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
env_logger = "0.8"
log = "0.4"
time = { version = "0.3", features = ["formatting"] }
notify = "4.0"
default-env = "0.1"
lazy_static = "1.4"
warp = "0.3"
prometheus = { version = "0.13", features = ["process"] }
futures = { version = "0.3", default-features = false }
tokio = "1.19"

[features]
# don't select systemd as default feature
default = []
systemd = ["sd-notify"]
